Update web3.py to version 6.14.0
Importing `autonity.py` on Python 3.12 fails due to

    ModuleNotFoundError: No module named 'pkg_resources'

triggered by web3.py. This is caused by web3.py's dependency on
setuptools that was fixed in version 6.14.0. [1]

[1]: https://web3py.readthedocs.io/en/stable/releases.html#web3-py-v6-14-0-2024-01-10

Fixes #42 and autonity/aut#141.