Fix import error with Python 12
Importing autonity.py on Python 3.12 failed due to

    ModuleNotFoundError: No module named 'pkg_resources'

triggered by Web3.py.

The error is caused by using too old version of `setuptools`.
`pkg_resources` was removed in version 39.0.0. [1]

Fixes #42.

[1]: https://setuptools.pypa.io/en/latest/history.html#v39-0-0